- hosts: nodes
  become: yes
  vars:
    user: vagrant
  tasks:
  - name:    Install prerequisites Cassandra
    apt:     name={{item}} update_cache=yes
    with_items:
     - openjdk-8-jre
     - openjdk-8-jdk
     - curl
     - software-properties-common
     - make
  - name:    Add Cassandra GPG key
    apt_key: url=https://www.apache.org/dist/cassandra/KEYS
  - name:    Add Cassandra APT repository
    apt_repository:
      repo: deb http://www.apache.org/dist/cassandra/debian 311x main state=present
  - name:    Install Cassandra
    apt: name=cassandra state=present update_cache=yes
  - name:   Make sure Cassandra is started
    service: name=cassandra state=restarted